### PR TITLE
modify things in views and add user experience enhancement

### PR DESCRIPTION
**Pull request by MehdiAroui**
I start to improve the views of the project

### CODE REVIEW

**Comment by changeweb** [comment]
This has some layout breaking changes like extra left side menu bar.

But the most important thing is Registering users from multiple places makes it confusing. For example, you can register student from Academic Settings page and as your change you can register them from the student list. I really appreciate your effort but the question is: Is it the change that most people want?

I think in latest codes all database seeder files work.

Moreover you only added url link for student and teacher list. Datatables for other pages don't get any action url passed. You can fix that too.

**Comment by MehdiAroui** [comment]
I saw that you can add students and techers from acad3mic settings but i found it a bit confusing, like, if I'm searching a studemt and I didn't find it, why don't add it just from where I am instead of navigating to academic settings.

I'll check the layout breaking for sure, cause there is more thibgs I think they should be improved.

Thank you for that great work.

**Comment by changeweb** [comment]
@MehdiAroui thanks for your concern about the improvement of the software. But please commit and make pull request with a small change. So that it gets easy for me to review the change and it will be good to manage any change.

Your pull request already has so much conflicts with the master branch. I request you to commit one small change at a time.

Can you share the screenshots of your changes please. Otherwise it is very time consuming and I may miss some changes.

**Comment by changeweb** [comment]
@MehdiAroui I've added a contribution guide line. Please see this [Contribution Guide line](https://github.com/changeweb/Unifiedtransform/blob/master/CONTRIBUTING.md)

**Comment by changeweb** [comment]
@MehdiAroui your pull request conflicts with so much files and layouts that it is difficult to resolve properly. So I'm closing this PR. It would be great if I can add those changes. Thanks for contributing.

**Pull request closed without merging**
