### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by rowild**
Restructure the introduction a little bit.
Fix some spelling and grammar errors.

### CODE REVIEW

**Comment by rowild** [comment]
Unfortunately, highlighting php code only works, when the code block is not indented. But that should be a minor problem...

**Comment by rowild** [comment]
It seems I cannot not propose a separate PR with the style improvement ideas, which are only meant for discussion. How can I separate them into 2 individual PRs?

**Comment by changeweb** [comment]
I don't think it's necessary to add PHP tag.
Please fix *veerfied* spelling.
And adding the word *account* after `Master` would be more proper I think.

For discussion you can create a new issue.

**Comment by changeweb** [comment]
I think in `register` page, go back to create school url should be `create-school` instead of `create`.

**Comment by rowild** [comment]
I will close this pull request and provide another one that only addresses the readme.

**Pull request closed without merging**
