### PR TITLE
propose better docker setup

### PR DESCRIPTION
**Pull request by handhikadj**
please take a look at this proposal especially on readme at: https://github.com/handhikadj/Unifiedtransform/blob/38ef46dc145a0ca272118730416e119493e98fa2/readme.md#using-docker-container

### CODE REVIEW

**Comment by changeweb** [comment]
@handhikadj please create a new pull request with only updated/new files. Readme.md is well-done.

This update will keep the project up to date! Have you tested this Docker setup in your machine?

**Comment by handhikadj** [comment]
of course I tested it out on my mac on docker for mac and it runs flawlessly
I updated readme.md so that people know how to use it. I only update stuff regarding what I've done on the proposal

**Comment by changeweb** [comment]
I know but the other unchanged files were also added in the Pull Request you made. I am suggesting to exclude those files in your new Pull Request.

**Comment by handhikadj** [comment]
it won't affect anything actually. they're only permission thingy.

**Comment by changeweb** [comment]
@handhikadj I am sorry for not reviewing your Pull Request early and for not properly thanking you for your contribution. I was a bit busy with my other works.

This is an important upgrade for those who want to use Docker. Good work 👍

**Comment by handhikadj** [comment]
never mind, bud. 
I use this docker setup in my day-to-day sysadmin even in production, regardless the system operation i'm running on

**Pull request merged**
