### PR TITLE
Added tests for Librarian Module.

### PR DESCRIPTION
**Pull request by fergthh**

### CODE REVIEW

**Comment by JuanVqz** [comment]
Hi @fergthh thanks for your support in pull requests #92 we talked about of the better practice. If you could use it we'll be thankfull.

What do you think? @changeweb

**Comment by changeweb** [comment]
@fergthh your build is failing for test can_see_some_personal_information.

**Comment by changeweb** [comment]
@JuanVqz it would be great if you could point out which part is not according to the better practice in this PR.

**Comment by JuanVqz** [comment]
@changeweb, @fergthh for me the name ```name('issued-books');``` it's wrong, I don't know but we will most be use one standard for two words in routes because **someone** could use ```ìssuedBooks.index``` or ```issued_books.index``` or ```ìssued.books.index``` or ```ìssuedbooks.index```
and in the uri that is correct? ```/issuedBooks``` or ```/ìssued_books``` or  ```/ìssued-books``` or  ```/issued/books``` or ```/ìssuedbooks```

for me the name would be ```name('issuedbooks.index`)```and the uri ```/issuedbooks``` only I would like to have a standard...

Or maybe all it's ok and I didn't talk about it, regards and thanks!

**Comment by fergthh** [comment]
Hi guys! First, @JuanVqz. You're right. The project must begin to follow a certain standard to avoid misunderstandings and mistakes. Thanks for indicating this. I think the `/issued-books` option is the right one.

Second. I'm going to check this today, @changeweb. I did not realize why the tests pass in php 7.1 and not version 7.2, or maybe it was just coincidence yet.

Sorry guys for the delay, the time zone is my nemesis.

Thank you both for the reviews.

**Comment by JuanVqz** [comment]
@fergthh perfect! Thx

**Pull request merged**
