### PR TITLE
test for create and store book

### PR DESCRIPTION
**Pull request by JuanVqz**
Not is necesary speficy table's name.

All attributes are required for create a new book?

Maybe is necesary put an * in required labels

### CODE REVIEW

**Comment by JuanVqz** [comment]
I'm sorry for push in this branch because you told me no more push in this put I had this changes yesterdey before you told me.

Thanks!

**Comment by changeweb** [comment]
Ok. I found a strategy on internet to merge new working features in dev_for_new_features branch.

Who wants to add a new feature must create a new branch and add the feature in that branch.

Then create a PR from that branch to changeweb:dev_for_new_features branch and then delete that branch.

**Comment by JuanVqz** [comment]
@changeweb I should push in other_branch with what father? Master or dev_for_new_features? Ok  I'll check the conflict.

**Comment by JuanVqz** [comment]
I closed this pull request #105 because I merged in to #106

**Pull request closed without merging**
