### PR TITLE
add books can be filter by school 

### PR DESCRIPTION
**Pull request by JuanVqz**

### CODE REVIEW

**Comment by changeweb** [comment]
I think this branch should also be kept up to date with master branch since sometimes direct bug fix PR is made and merged. So if this branch is not kept up to date then that bug will still remain in this branch and will make the changes inappropriate while merging this branch on master.

**Comment by JuanVqz** [comment]
You are right! How to I can do this? I'm new pulling in a other repository I'm learning.

For example in this case I have to make two pull request my first pull request my_branch to master with Book.php BookTest.php and other into dev_for_new_features with Library\BookController.php

Or you have any example?

**Comment by changeweb** [comment]
I will do the pull request work after ensuring that this branch's changes are ok. We need to wait for writing new changes before previous changes get merged. It will separate a working new change from a coming new change.

What do you think?

**Comment by JuanVqz** [comment]
For example just right now I can push a new component for `panel-table` for replace tables into panel-body I should push over master or dev_for_new_feature, I think it's usable in master.

**Comment by changeweb** [comment]
Yes we can do that. But I've already merged some changes of yours to dev_for_new_feature.

To resolve this issue, don't push any more changes to this branch right now. First we have to make sure the changes we made in this branch work properly. Then I will merge it and we should be discrete about pushing any new changes.

What do you think?

**Pull request merged**
