### PR TITLE
Add Laravel Impersonation

### LINKED ISSUE #117: Add Impersonation
**Is your feature request related to a problem? Please describe.**
When testing, I have to logout and login as the user I need to use. 

**Describe the solution you'd like**
With [Laravel Impersonate](https://github.com/404labfr/laravel-impersonate), I can pick a user I'd like to impersonate and see the application through that user's eyes. This is really helpful when testing.

We can have an "Impersonate" link/button on the user profile dropdown at the top-right of the screen, allowing the user to select a user besides themselves to impersonate.

**Additional context**
This feature can be made only accessible in dev/staging environment, for security reasons. 

A more advanced approach will be allowing users in a higher role/state-hierarchy to impersonate users under them. E.g. A `master` should be able to impersonate any of

- admin
- accountant
- librarian
- teacher
- student 

An admin can only impersonate 

- accountant
- librarian
- teacher
- student

### PR DESCRIPTION
**Pull request by mykeels**
With this, we can simulate any user in the system. Should fix #117 

### Here's the Impersonation menu

image

### Here's what the Impersonate Users view looks like

image

### Here's the Leave Impersonation Menu
image

### CODE REVIEW

**Comment by changeweb** [comment]
Wow. So it works. But we have to ensure that it is only for Dev environment. What is your plan on that?

**Comment by changeweb** [comment]
So after ensuring that it only works for Dev, I will merge it. Thanks.

**Comment by mykeels** [comment]
I'll update the PR to reflect that. I plan to use the .env variable.

**Comment by mykeels** [comment]
Done!

**Comment by mykeels** [comment]
Done!

**Comment by changeweb** [comment]
Sorry for bothering you but can you add a short documentation on it in readme before I merge it?

**Comment by mykeels** [comment]
Sure, no problem!

**Comment by mykeels** [comment]
Done!

**Pull request merged**
