### PR TITLE
feat: add docker-compose.yml

### LINKED ISSUE #52: Docker Compose
It will be much easier if you can dockerize and make it seamless

### PR DESCRIPTION
**Pull request by mykeels**
## This should fix #52 

This might need some improvement, but this docker setup works.

Additional setup commands will be to be run after `docker-compose up -d`, to perform actions such as seeding the database.

The web server will run at port 9000 when the containers are up and running.

Let me know what you think.

### CODE REVIEW

**Comment by changeweb** [comment]
@mykeels I've very little knowledge of Docker but your changes seems right.
Can you please write down the steps to reproduce the Docker experience you are creating?
Besides, I see you added Nginx configuration for Docker. Can you add one for Apache server?

I need to know the steps about how to run this and I've to add these instructions as Documentation.
Thanks for your contributions. I love open source community for this.

**Comment by mykeels** [comment]
Okay, are you saying you'd prefer the Apache server to nginx? Or you want docker setups for both?

**Comment by changeweb** [comment]
It would be great to have Docker configuration for both.

**Comment by changeweb** [comment]
@mykeels thanks a lot for Docker implementation. I've learned a lot about Docker by studying your added files.

**Comment by mykeels** [comment]
Hi @changeweb, I'm glad to help. I just saw you'd merged this. Do you still need the Apache implementation?

**Comment by changeweb** [comment]
I think since it is containerized so it should run properly in any platform independently without any specific server requirement. So Nginx will do the job I guess. Am I right?

**Comment by mykeels** [comment]
Yep, you're right. It should do it independently.

**Comment by AfolabiOlaoluwa** [comment]
I actually don't think you need Apache since everything is lovely containerized by @mykeels with Nginx. Nginx will do the job. Nethertheless, if you still want to add Apache container, something close to this should be fine for port 80 and secured port 443 for production. You could extend it further as you desire.

```
apache2:
        image: webdevops/apache:latest # webdevops apache image box
        args:
            - PHP_SOCKET=php:9000
        volumes:
            - ./php/www:/var/www/html
        ports:
            - 80:80
            - 443:443
        links:
            - php # this being the php container firstly defined in the docker-compose file. if necessary
```

Also you could network this too if needed.
```
networks:
      - app-network
```
As well as make it dependent on the defined database service
```
depends_on:
      - you_can_put_the_database_container_service_here
```

....just a pointer to be tailored anyway...but I surely will go for Nginx which @mykeels defined any day, any time over Apache. Well done.

**Comment by mykeels** [comment]
After running `docker-compose up -d`, you'll want to make sure the `DB_HOST` in your `.env` file is set to `db`, which is the container name of the mysql instance.

Also, run the following:

```sh
docker-compose exec app php artisan config:cache
docker-compose exec app php artisan migrate
docker-compose exec app php artisan key:generate
docker-compose exec app php artisan db:seed
```

If you'd like to begin a terminal session in any of the containers, use 

```sh
docker-compose exec <container-name> bash -l
```
e.g.
```sh
docker-compose exec app bash -l
```

**Comment by mykeels** [comment]
At this point, it should be possible to run `http://localhost:9000` in your browser, and login with the `master` role account you specified in the `UsersTableSeeder.php` file.

**Pull request merged**
